### PR TITLE
Add enable/disable FA commands and event.

### PR DESCRIPTION
**Pull request by pkubanek**

### CODE REVIEW

**Review by rbovill — APPROVED** [review]
Addition of new commands looks good.

**Review by rbovill — CHANGES_REQUESTED** [review]
The \<Item\> tag for the new commands is using a capital I; it should be lowercase.

**Comment by pkubanek** [comment]
Thanks for catching it up. Of course Item doesn't produced expected result with C++ code (the item was missing in headers& c code). Fixed.

**Review by tribeiro — APPROVED** [review]
looks good!

**Pull request merged**
