### PR TITLE
added mask rotation command

### PR DESCRIPTION
**Pull request by parfa30**

### CODE REVIEW

**Review by couger01 — APPROVED** [review]
LGTM, doc CI failures are unrelated.

**Comment by parfa30** [comment]
so what do I do about the CI failures? Will those be fixed for me and then merged when the next release occurs?

**Comment by couger01** [comment]
I made a ticket for the docs ci. The unit tests are passing and those are the only required CI that need to pass in order to merge.

**Review by couger01 — CHANGES_REQUESTED** [review]
You need to update the version history.

**Review by couger01 — APPROVED** [review]
LGTM.

**Pull request merged**
