### PR TITLE
DM-27228: FA bump test

### PR DESCRIPTION
**Pull request by pkubanek**
Added bump test and kill bump test commands and bump test status event.

### CODE REVIEW

**Review by rbovill — CHANGES_REQUESTED** [review]
Please remove the <Alias> tags from all topic definitions.  This field was removed from the schema.

**Comment by pkubanek** [comment]
> Please remove the tags from all topic definitions. This field was removed from the schema.

Can you be more specific? I am not sure what to remove. Thanks.

**Comment by pkubanek** [comment]
> Please remove the tags from all topic definitions. This field was removed from the schema.

Fixed - Alias removed. As noted on slack, xmllint can do XSD validation and is used in GitHub action. It might make sense to use it in GitHub action for events etc. validations..

**Review by rbovill — APPROVED** [review]
Changes look good and the unit tests are passing.

**Pull request merged**
