### PR TITLE
DM-30710: xmllint pre-commit check configuration file

### PR DESCRIPTION
**Pull request by pkubanek**

### CODE REVIEW

**Review by r-owen — CHANGES_REQUESTED** [review]
If possible, please:
* Make this run with the pre-commit package (updating .pre-commit-config.yaml accordingly)
* Make this actually apply the formatting, like the pre-commit black and isort packages. This seems to be standard behavior and it's especially useful for xmllint because the command to reformat xml with xmllint is very complicated and difficult to remember.

**Comment by pkubanek** [comment]
pre-commit hook moved to own repo at https://github.com/lsst-ts/pre-commit-xmllint. This PR now only reformats xsd files (those are xml as well; I actually used *pre-commit try-repo* to reformat files, proving hook works as expected).

**Review by r-owen — APPROVED** [review]
It works well but gives the following scary warning:

[WARNING] The 'rev' field of repo 'https://github.com/lsst-ts/pre-commit-xmllint' appears to be a mutable reference (moving tag / branch).  Mutable references are never updated after first install and are not supported.  See https://pre-commit.com/#using-the-latest-version-for-a-repository for more details.

I suggest you release the hook first (I'm about to review it) and then change the reference in ts_xml before merging this.

**Comment by pkubanek** [comment]
I know about warning. Will switch to tag once pre-commit-xmllint is merged and tag is there, rebase ts_xml and commit it.

**Pull request merged**
