### PR TITLE
CAP-833: Delete AdamSensors

### PR DESCRIPTION
**Pull request by r-owen**

### CODE REVIEW

**Comment by wvreeven** [comment]
Has it been decided to completely remove AdamSensors? It is still present in ts_cycle_build.

**Comment by mareuter** [comment]
It was granted removal from the XML interface. We will remove it from the cycle build as part of cycle 26 work.

**Comment by wvreeven** [comment]
Thanks for the clarification!

**Review by rbovill — APPROVED** [review]
Approved.

**Pull request merged**
