### PR TITLE
add Telemetry entries for FA pressure readout

### PR DESCRIPTION
**Pull request by pkubanek**

### CODE REVIEW

**Review by rbovill — CHANGES_REQUESTED** [review]
Need to address the failing unit tests; Description and Unit fields cannot be blank.

**Comment by pkubanek** [comment]
Added units and description. Shall be fine now.

**Comment by rbovill** [comment]
Can you rebase and squash the commits?

**Review by rbovill — APPROVED** [review]
Tests are passing.  LGtM.

**Pull request merged**
