### PR TITLE
Fix AT/MT Ptg lack of units on mountStatus telemetry topic.

### PR DESCRIPTION
**Pull request by tribeiro**

### CODE REVIEW

**Review by rbovill — CHANGES_REQUESTED** [review]
Please update the test_IDL_Type.py unit test to remove the now fixed Jira tickets.

**Comment by tribeiro** [comment]
Alright... nice catch... thanks...

**Review by rbovill — CHANGES_REQUESTED** [review]
Missed the mountRotError attribute in ATPtg_Telemetry.xml

**Review by rbovill — APPROVED** [review]
Changes look good to me.

**Pull request merged**
