### PR TITLE
DM-25909: Update telemetry topics in ATPtg and MTPtg to publish values as floats instead of sexagesimal strings

### PR DESCRIPTION
**Pull request by tribeiro**
Update pointing component interface to replace string for double in topic attributes with values.

### CODE REVIEW

**Comment by pkubanek** [comment]
Off this topics: it doesn't look good to send MJD and JD. Choose one, MJD preferred. See:

```
    <item>
        <EFDB_Name>jd</EFDB_Name>
        <Description>Julian date in days</Description>
        <IDL_Type>double</IDL_Type>
        <Units>day</Units>
        <Count>1</Count>
    </item>
    <item>
        <EFDB_Name>mjd</EFDB_Name>
        <Description>Modified Julian Data in days</Description>
        <IDL_Type>double</IDL_Type>
        <Units>day</Units>
        <Count>1</Count>
    </item>
```

**Comment by pkubanek** [comment]
*off this topic, new issue?* Also it's better to have wrap as int (I don't expect to see |wrap| > 2):

```
    <item>
        <EFDB_Name>mountAzCurrentWrap</EFDB_Name>
        <Description>Mount azimuth axis current wrap</Description>
        <IDL_Type>long</IDL_Type>
        <!-- <Enumeration> Wraps </Enumeration> -->
        <Units>unitless</Units>
        <Count>1</Count>
    </item>
    <item>
        <EFDB_Name>mountRotCurrentWrap</EFDB_Name>
        <Description>Rotator current wrap</Description>
        <IDL_Type>long</IDL_Type>
        <!-- <Enumeration> Wraps </Enumeration> -->
        <Units>unitless</Units>
        <Count>1</Count>
    </item>
```

**Comment by ayayoshimura** [comment]
Shouldn't the units of the utc and localTime (timeAndDate Telemetry) be 'day' instead of 'hour'?

**Comment by ayayoshimura** [comment]
Maybe units of the mountStatus's mountRA should be changed to 'hour'?

**Pull request merged**
