### PR TITLE
First pass of units and descriptions for

### PR DESCRIPTION
**Pull request by couger01**
- ATAOS
- ATMonochromator
- ATSpectrograph
- ATTCS
- DIMM
- Electrometer

### CODE REVIEW

**Comment by rbovill** [comment]
- ATSpectrograph Commands: ATSpectrograph_command_changeDisperser topic, disperser attribute is missing a Description
- ATSpectrograph Events: ATSpectrograph_logevent_settingsApplied topic, linearStageSpeed attribute is missing Units
- DIMM Events: DIMM_logevent_dimmData topic, averageEllipticityspot1 attribute, looks like the Description was put into Units field
- DIMM_logevent_dimmMeasurement topic, flux, fluxL and fluxR attributes define ADU as the unit, but this isn't recognized by astropy

**Comment by rbovill** [comment]
In DIMM Events, several attributes are missing Units: detailedState, loopTimeOutOfRange, scintL, strehlL

**Comment by tribeiro** [comment]
I think you probably need to rebase to develop. There are some errors on the CI job https://ts-ci.lsst.codes/job/lsst-ts/job/ts_xml/view/change-requests/job/PR-120/5/console.

**Comment by tribeiro** [comment]
In fact, seems like it is worse than that. There are other errors mixed there.

**Pull request merged**
